server:
  port: 8081
spring:
  application:
    name: hello-server
  profiles: default
  profiles.active: dev
eureka:
  instance:
    hostname: localhost
    appname: ${spring.application.name}
    instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8671/eureka/
    instance:
      hostname: localhost
      nonSecurePort: 8081
---
server:
  port: 8081
spring:
  application:
    name: hello-server
  profiles: dev
  profiles.active: dev
eureka:
  instance:
    hostname: localhost
    appname: ${spring.application.name}
    instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://replicas2:8762/eureka/,http://replicas3:8763/eureka/
    instance:
      hostname: localhost
      nonSecurePort: 8081
---
server:
  port: 8082
spring:
  application:
    name: hello-server
  profiles: uat
  profiles.active: uat
eureka:
  instance:
    hostname: localhost
    appname: ${spring.application.name}
    instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://replicas2:8762/eureka/,http://replicas3:8763/eureka/
    instance:
      hostname: localhost
      nonSecurePort: 8082