spring:
  application:
    name: hello-server
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8671/eureka/
    instance:
      hostname: localhost
      nonSecurePort: 8080