spring:
  application:
    name: spring-vault-config
server:
  port: 8080
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8671/eureka/
    instance:
      hostname: localhost