spring:
  application:
    name: git-config-server
  jackson:
    serialization:
      indent_output: true
  profiles: default
  profiles.active: dev
# It will start server conventional port 8888
  config:
    name: configserver
management:
  endpoint:
    health:
      enabled: true
      show-details: always
    shutdown:
      enabled: true
    info:
      enabled: true
  endpoints:
    web:
      base-path: /
      # By default, only 'health' and 'info' are accessible via web
      exposure:
        include: '*'