spring:
  application:
    name: eureka-service
  /profiles:
    profiles: replicas2
    active: replicas2
server:
  port: 8762
eureka:
  instance:
    hostname: localhost
    appname: eureka-cluster
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://replicas1/eureka/,http://replicas3/eureka/
    server:
      waitTimeInMsWhenSyncEmpty: 0