# This default profile is used when running a single instance completely standalone:
---
spring:
  application:
    name: eureka-service
  /profiles:
    profiles: default
    active: default
server:
  port: 8671
eureka:
  datacenter: default
  environment: default
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    server:
      waitTimeInMsWhenSyncEmpty: 0

# replicas1, replicas2, and replicas3 illustrate running 3 intercommunicating instances.
# This example has them running side-by-side on localhost
# -- which is unrealistic in production
# -- but does illustrate how multiple instances collaborate.
#
# Run by opening 3 separate command prompts:
# java -jar -Dspring.profiles.active=replicas1 eureka-service-0.0.1-SNAPSHOT.jar
# java -jar -Dspring.profiles.active=replicas2 eureka-service-0.0.1-SNAPSHOT.jar
# java -jar -Dspring.profiles.active=replicas3 eureka-service-0.0.1-SNAPSHOT.jar
---
spring:
  application:
    name: eureka-service
  /profiles:
    profiles: replicas1
    active: replicas1
server:
  port: 8761
eureka:
  instance:
    hostname: localhost
    appname: eureka-cluster
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://replicas2/eureka/,http://replicas3/eureka/
    server:
      waitTimeInMsWhenSyncEmpty: 0
---
spring:
  application:
    name: eureka-service
  /profiles:
    profiles: replicas2
    active: replicas2
server:
  port: 8762
eureka:
  instance:
    hostname: localhost
    appname: eureka-cluster
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://replicas1/eureka/,http://replicas3/eureka/
    server:
      waitTimeInMsWhenSyncEmpty: 0
---
spring:
  application:
    name: eureka-service
  /profiles:
    profiles: replicas3
    active: replicas3
server:
  port: 8763
eureka:
  instance:
    hostname: localhost
    appname: eureka-cluster
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://replicas1/eureka/,http://replicas2/eureka/
    server:
      waitTimeInMsWhenSyncEmpty: 0