spring:
  application:
    name: eureka-service
  /profiles:
    profiles: replicas3
    active: replicas3
server:
  port: 8763
eureka:
  instance:
    hostname: localhost
    appname: eureka-cluster
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://replicas1/eureka/,http://replicas2/eureka/
    server:
      waitTimeInMsWhenSyncEmpty: 0