spring:
  application:
    name: eureka-service
  /profiles:
    profiles: replicas1
    active: replicas1
server:
  port: 8761
eureka:
  instance:
    hostname: localhost
    appname: eureka-cluster
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://replicas2/eureka/,http://replicas3/eureka/
    server:
      waitTimeInMsWhenSyncEmpty: 0