# This default profile is used when running a single instance completely standalone:
---
spring:
  application:
    name: eureka-service
  /profiles:
    profiles: default
    active: replicas1
server:
  port: 8671
eureka:
  datacenter: default
  environment: default
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    server:
      waitTimeInMsWhenSyncEmpty: 0
management:
  endpoint:
    health:
      enabled: true
      show-details: always
    shutdown:
      enabled: true
  endpoints:
    web:
      base-path: /
      # By default, only 'health' and 'info' are accessible via web
      exposure:
        include: '*'
