spring:
  application:
    name: eureka-service
  /profiles:
    profiles: replicas2
    active: replicas2
server:
  port: 8762
eureka:
  datacenter: replicas2
  environment: replicas2
  instance:
    hostname: replicas2
    appname: eureka-cluster
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://replicas1:8761/eureka/,http://replicas3:8763/eureka/
    server:
      waitTimeInMsWhenSyncEmpty: 0
management:
  endpoint:
    health:
      enabled: true
      show-details: always
    shutdown:
      enabled: true
  endpoints:
    web:
      base-path: /
      # By default, only 'health' and 'info' are accessible via web
      exposure:
        include: '*'