spring:
  application:
    name: hello-client
  profiles: default
  profiles.active: dev
server:
  port: 8086
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8671/eureka/
  instance:
    hostname: localhost
    appname: ${spring.application.name}
    instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}
---
spring:
  application:
    name: hello-client
  profiles: dev
  profiles.active: dev
server:
  port: 8086
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://replicas2:8762/eureka/,http://replicas3:8763/eureka/
  instance:
    hostname: localhost
    appname: ${spring.application.name}
    instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}
---
spring:
  application:
    name: hello-client
  profiles: uat
  profiles.active: uat
server:
  port: 8087
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://replicas2:8762/eureka/,http://replicas3:8763/eureka/
  instance:
    hostname: localhost
    appname: ${spring.application.name}
    instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}