spring:
  application:
    name: git-config-client
  profiles: default
  profiles.active: dev
server:
  port: 8084
eureka:
  instance:
    hostname: localhost
    appname: ${spring.application.name}
    instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8671/eureka/
    instance:
      hostname: localhost
---
spring:
  application:
    name: git-config-client
  profiles: dev
  profiles.active: dev
server:
  port: 8084
eureka:
  instance:
    hostname: localhost
    appname: ${spring.application.name}
    instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://replicas2:8762/eureka/,http://replicas3:8763/eureka/
    instance:
      hostname: localhost
---
spring:
  application:
    name: git-config-client
  profiles: uat
  profiles.active: uat
server:
  port: 8085
eureka:
  instance:
    hostname: localhost
    appname: ${spring.application.name}
    instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://replicas2:8762/eureka/,http://replicas3:8763/eureka/
    instance:
      hostname: localhost